language: python

dist: xenial

sudo: required

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - HYDRA_LAUNCHER=fork
    - OMPI_MCA_plm=isolated
    - OMPI_MCA_rmaps_base_oversubscribe=true
    - NP=20
  matrix:
    - MPI=mpich
    # - MPI=openmpi

matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
        - MPI=mpich
    # - python: '3.6'
    #   env:
    #     - TOXENV=docs
    - python: '3.6'
      env:
        - TOXENV=py36
        # - TOXENV=py36,codecov
        - MPI=mpich
    - python: '3.7'
      env:
        - TOXENV=py37
        # - TOXENV=py37,codecov
        - MPI=mpich
    - python: '3.8'
      env:
        - TOXENV=py38
        # - TOXENV=py38,codecov
        - MPI=mpich

cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    update: true

before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - bash ci/travis-ci/install-mpi.sh $MPI
  - if [[ "$MPI" == "mpich"   ]]; then mpichversion; fi

install:
  - python -mpip install --progress-bar=off tox -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
